"""Derive website selections from hand-maintained bilingual READMEs. No dependencies."""
from __future__ import annotations
import argparse
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
START, END = "<!-- curated:start -->", "<!-- curated:end -->"
ENTRY = re.compile(r"^- \[([^\]]+)\]\((https://[^\s)]+)\) - (.+)$")


def parse_readme(text: str) -> list[dict[str, str]]:
    if text.count(START) != 1 or text.count(END) != 1 or text.index(START) > text.index(END):
        raise ValueError("Expected exactly one ordered curated marker pair.")
    block = text.split(START, 1)[1].split(END, 1)[0]
    category, rows, seen = "", [], set()
    for line in block.splitlines():
        if line.startswith("## "):
            category = line[3:].strip()
        elif line.startswith("- "):
            match = ENTRY.fullmatch(line)
            if not category or not match:
                raise ValueError(f"Malformed resource or missing category: {line}")
            name, url, description = match.groups()
            key = url.rstrip("/").casefold()
            if key in seen:
                raise ValueError(f"Duplicate resource: {url}")
            seen.add(key)
            rows.append(dict(name=name, url=url, description=description, category=category))
        elif line.strip():
            raise ValueError(f"Unexpected content inside curated block: {line}")
    if not rows:
        raise ValueError("The curated block must not be empty.")
    return rows


def build_catalog(en: str, zh: str) -> dict:
    english, chinese = parse_readme(en), parse_readme(zh)
    if [r["url"] for r in english] != [r["url"] for r in chinese]:
        raise ValueError("English and Chinese selections must have identical URLs and order.")
    categories = {}
    for a, b in zip(english, chinese):
        previous = categories.setdefault(a["category"], b["category"])
        if previous != b["category"]:
            raise ValueError("A category was split inconsistently between translations.")
    if len(set(categories.values())) != len(categories):
        raise ValueError("Category translations must map one-to-one.")
    return {
        "schema_version": 1,
        "source": "README.md + README_zh.md; generated by scripts/sync_catalog.py",
        "entries": [{"url": a["url"], "en": {k:v for k,v in a.items() if k != "url"},
                     "zh": {k:v for k,v in b.items() if k != "url"}}
                    for a,b in zip(english, chinese)],
    }


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail rather than write if data is stale")
    args = parser.parse_args(argv)
    try:
        data = build_catalog((ROOT / "README.md").read_text(encoding="utf-8"),
                             (ROOT / "README_zh.md").read_text(encoding="utf-8"))
        output = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
        path = ROOT / "docs/data/curated.json"
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != output:
                print("Website selections are stale. Run: python3 scripts/sync_catalog.py")
                return 1
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(output, encoding="utf-8")
        print(f"OK: {len(data['entries'])} bilingual selections")
        return 0
    except (OSError, ValueError) as exc:
        print(f"Catalog check failed: {exc}")
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
